nnunet_raw: /root/autodl-tmp/datasets/nnUNet_raw
nnunet_preprocessed: /root/autodl-tmp/datasets/preprocessed
nnunet_results: /root/autodl-tmp/datasets/nnunet_results
nnunet_data: /root/autodl-tmp/datasets
caption_csv_train: /autodl-tmp/caption_train_private_v5_ord_all_clean.csv
caption_csv_val: /autodl-tmp/caption_val_private_v5_ord_all_clean.csv
caption_csv_val_public_kits19: /autodl-tmp/caption_val_linux.csv
caption_prompt_json: null
nnunet_encoder_checkpoint: null
mamba_hf_model: /autodl-tmp/models/mamba-2.8b-hf
global_pool_size_3d:
- 4
- 4
- 4
local_crop_size_3d:
- 2
- 5
- 10
patch_size_3d:
- 32
- 128
- 128
